dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  closedloopik_control:
    type: dualarm_controller/ClosedLoopIK_Control
    joints:
      - dualarm_joint1
      - dualarm_joint2
      - dualarm_joint3
      - dualarm_joint4
      - dualarm_joint5
      - dualarm_joint6
      - dualarm_joint7
      - dualarm_joint8
      - dualarm_joint9
      - dualarm_joint10
      - dualarm_joint11
      - dualarm_joint12
      - dualarm_joint13
      - dualarm_joint14
      - dualarm_joint15
      - dualarm_joint16

    root_link: world
    tip_link1: dualarm_R_end_frame
    tip_link2: dualarm_L_end_frame

    gains:
      dualarm_joint1:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint2:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint3:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint4:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint5:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint6:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint7:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint8:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint9:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint10:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint11:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint12:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint13:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint14:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint15:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}
      dualarm_joint16:
        pid: {p: 20.0, i: 100.0, d: 1, h: 10.0}

    clik_gain: { K_pos: 0.1, K_ori: 0.1 }

    ctr_obj: 1  # Index2
                # 1 : Jacobian PseudoInverse
                # 2 : Jacobian Transpose
                # 3 : damped Jacobian PseudoInverse
                # 4 : Scaled Jacobian Transpose
                # 5 : Block Jacobian PseudoInverse
                # 6 : Weight damped Jacobian PseudoInverse without q0dot
                # 7 : Jacobian PseudoInver with Relative Jacobian(left-hand)

    ik_mode: 2  # SubIndex
                # 2 : x-axis
                # 3 : y-axis
                # 4 : relative motion (base:right-hand, end:left-hand)
                # 5 : designed set-point
                # 6 : given position from rqt

