dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  computedtorque_control_clik:
    type: dualarm_controller/ComputedTorque_Control_CLIK
    joints:
      - dualarm_joint1
      - dualarm_joint2
      - dualarm_joint3
      - dualarm_joint4
      - dualarm_joint5
      - dualarm_joint6
      - dualarm_joint7
      - dualarm_joint8
      - dualarm_joint15
      - dualarm_joint9
      - dualarm_joint10
      - dualarm_joint11
      - dualarm_joint12
      - dualarm_joint13
      - dualarm_joint14

    gains:
      dualarm_joint1:
        pid: {p: 10.0, i: 7.4, d: 2}
      dualarm_joint2:
        pid: {p: 10.0, i: 32.10, d: 2}

      dualarm_joint3:
        pid: {p: 10.0, i: 11.55, d: 2}
      dualarm_joint4:
        pid: {p: 10.0, i: 11.65, d: 2}
      dualarm_joint5:
        pid: {p: 10.0, i: 11.25, d: 2}
      dualarm_joint6:
        pid: {p: 10.0, i: 11.20, d: 2}
      dualarm_joint7:
        pid: {p: 10.0, i: 13.20, d: 2}
      dualarm_joint8:
        pid: {p: 10.0, i: 20.01, d: 2}
      dualarm_joint9:
        pid: {p: 10.0, i: 12.55, d: 2}
      dualarm_joint10:
        pid: {p: 10.0, i: 12.65, d: 2}
      dualarm_joint11:
        pid: {p: 10.0, i: 21.25, d: 2}
      dualarm_joint12:
        pid: {p: 10.0, i: 17.20, d: 2}
      dualarm_joint13:
        pid: {p: 10.0, i: 18.20, d: 2}
      dualarm_joint14:
        pid: {p: 10.0, i: 18.01, d: 2}
      dualarm_joint15:
        pid: {p: 10.0, i: 2.01, d: 2}


    root_link: world
    tip_link1: link_R_hand
    tip_link2: link_L_hand

    ctr_obj: 0

    ik_mode: 1

    clik_gain: {K_regulation: 1.0, K_tracking: 0.00005}