dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  impedance_control:
    type: dualarm_controller/Impedance_Control
    joints:
      - dualarm_joint1
      - dualarm_joint2
      - dualarm_joint3
      - dualarm_joint4
      - dualarm_joint5
      - dualarm_joint6
      - dualarm_joint7
      - dualarm_joint8
      - dualarm_joint9
      - dualarm_joint10
      - dualarm_joint11
      - dualarm_joint12
      - dualarm_joint13
      - dualarm_joint14
      - dualarm_joint15
      - dualarm_joint16

    root_link: world
    tip_link1: dualarm_R_end_frame
    tip_link2: dualarm_L_end_frame

    desired:
      mass: { m1: 3.0, m2: 3.0 } # unit:kg, shape:ellipsoid (for inertia shaping)
    gains:
      mbk: { KpT: 20.0, KpR: 1.0, KdT: 1.0, KdR: 0.05 } # gains for spring & damper

    target_obj: 2 # 1 : x-axis
                  # 2 : y-axis
                  # 3 : z-axis
                  # 4 : pre-defined

    ctrl_type: 2  # 1 : Mx_desired = Mx_actual
                  # 2 : Mx_desired != Mx_actual (need ft_sensor)
                  # 3 : Relative Impedance

