dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  impedance_control:
    type: dualarm_controller/Impedance_Control
    joints:
      - dualarm_joint1
      - dualarm_joint2
      - dualarm_joint3
      - dualarm_joint4
      - dualarm_joint5
      - dualarm_joint6
      - dualarm_joint7
      - dualarm_joint8
      - dualarm_joint9
      - dualarm_joint10
      - dualarm_joint11
      - dualarm_joint12
      - dualarm_joint13
      - dualarm_joint14
      - dualarm_joint15
      - dualarm_joint16

    desired:
      mass: { m1: 0.8, m2: 0.1 } # unit:kg, shape:ellipsoid (for inertia shaping)

    gains:
      mbk: { KpT: 1.2, KpR: 0.01, KdT: 0.07, KdR: 0.002 } # gains for spring & damper

    root_link: world
    tip_link1: dualarm_R_end_frame
    tip_link2: dualarm_L_end_frame

    target_obj: 2 # 1 : x-axis
                  # 2 : y-axis
                  # 3 : z-axis
                  # 4 : pre-defined

    ctrl_type: 1  # 1 : Mx_desired = Mx_actual
                  # 2 : Mx_desired != Mx_actual (need ft_sensor)

